### PR TITLE
Add slots available dashboard

### PR DESCRIPTION
**Pull request by meoflynn**
### Description:

This is based on an existing dashboard, where the rows have been added to group flavors together and thresholds for panel displays updated.

### Submitter:

Have you:

* [x] Checked the latest commit runs on a Grafana instance using the aq personality `openstack-grafana`?
  
* [x] Dashboards have clearly labelled panels, and are easy to read?

### Reviewer:

As part of reviewing this PR the changes must be tested on a Grafana instance. To do this:

* [x] Spin up a machine with the aq personality `openstack-grafana`

* [x] Open Grafana and navigate to browse dashboard

* [x] You should see the dashboards which are from this repo

* [x] Import any dashboards that have been added or modified in this PR to Grafana.
  
Have you:

* [x] Checked whether the panels are clear and easy to read?

### CODE REVIEW

**Review by anish-mudaraddi — CHANGES_REQUESTED** [review]
Nit: Is there a way to put dividers between values and headings. Its okay for the most part - but here it's a little confusing 

image

**Comment by anish-mudaraddi** [comment]
Also - is that supposed to be -1?
image

**Comment by meoflynn** [comment]
The panels are not meant to report negative values, the values are from the main query so I think there might be an issue with how the data is collected for that flavors in that specific panel?

**Review by anish-mudaraddi — APPROVED** [review]
looks good :+1:

**Pull request merged**
